Repository handong-app/handong-feed-app, pull requests merged in 2025-04, with the labels that each got.

#95 feat: 외부 API에 대한 API-Key 인증 및 Scope 기반 권한 제어 기능 도입
  .bruno/Feed/External/folder.bru
  .bruno/Feed/External/newsletter/Read All Tag.bru
  .bruno/Feed/External/newsletter/Read Tag.bru
  .bruno/Feed/External/newsletter/folder.bru
  .bruno/Feed/External/spotlight/folder.bru
  .bruno/environments/Local.bru
  src/main/java/app/handong/feed/config/WebMvcConfig.java
  src/main/java/app/handong/feed/controller/external/NewsletterExternalApiController.java
  src/main/java/app/handong/feed/controller/external/SpotlightExternalApiController.java
  src/main/java/app/handong/feed/exception/GlobalExceptionHandler.java
  src/main/java/app/handong/feed/exception/data/DuplicateTagCodeException.java
  src/main/java/app/handong/feed/exception/data/NoMatchingDataException.java
  src/main/java/app/handong/feed/interceptor/ApiKeyAuthInterceptor.java
  src/main/java/app/handong/feed/repository/ApiKeyRepository.java
  src/main/java/app/handong/feed/security/annotation/RequiredScopes.java
  src/main/java/app/handong/feed/service/impl/TagServiceImpl.java
Labels: enhancement

#99 ♻️ refactor: unify NotFound-related exceptions and clean up references
  src/main/java/app/handong/feed/exception/GlobalExceptionHandler.java
  src/main/java/app/handong/feed/exception/data/DuplicateEntityException.java
  src/main/java/app/handong/feed/exception/data/NotFoundException.java
  src/main/java/app/handong/feed/service/impl/TagServiceImpl.java
Labels: enhancement

#114 ♻️ refactor: api key schema
  .bruno/Feed/Admin/issue api key.bru
  src/main/java/app/handong/feed/domain/ApiKey.java
  src/main/java/app/handong/feed/domain/ApiKeyScope.java
  src/main/java/app/handong/feed/dto/TbadminDto.java
  src/main/java/app/handong/feed/service/impl/TbadminServiceImpl.java
Labels: enhancement

#119 [BE] feat: update lastUsedAt field only when API key access is authorized
  src/main/java/app/handong/feed/domain/ApiKey.java
  src/main/java/app/handong/feed/interceptor/ApiKeyAuthInterceptor.java
Labels: enhancement

#127 [BE/Refactor] 유저 권한 확인 로직 Annotation 방식으로 변경
  .bruno/Feed/Admin/ApiKey/delete api key.bru
  .bruno/Feed/Admin/ApiKey/folder.bru
  .bruno/Feed/Admin/ApiKey/get all.bru
  .bruno/Feed/Admin/ApiKey/issue api key.bru
  .bruno/Feed/Admin/ApiKey/toggle api key status.bru
  .bruno/Feed/Admin/Users/All Users.bru
  .bruno/Feed/Admin/Users/folder.bru
  build.gradle
  checkstyle.xml
  src/main/java/app/handong/feed/config/FirebaseConfig.java
  src/main/java/app/handong/feed/config/RewriteFilter.java
  src/main/java/app/handong/feed/config/WebMvcConfig.java
  src/main/java/app/handong/feed/controller/DefaultController.java
  src/main/java/app/handong/feed/controller/LabSSEController.java
  src/main/java/app/handong/feed/controller/TbadminController.java
  src/main/java/app/handong/feed/controller/external/NewsletterExternalApiController.java
  src/main/java/app/handong/feed/controller/page/ShareMetaPageController.java
  src/main/java/app/handong/feed/domain/TbUserReadAll.java
  src/main/java/app/handong/feed/domain/TbUserSearch.java
  src/main/java/app/handong/feed/interceptor/ApiKeyAuthInterceptor.java
  src/main/java/app/handong/feed/interceptor/DefaultInterceptor.java
  src/main/java/app/handong/feed/repository/TbUserPermRepository.java
  src/main/java/app/handong/feed/repository/TbUserReadAllRepository.java
  src/main/java/app/handong/feed/security/annotation/RequiredApiScopes.java
  src/main/java/app/handong/feed/security/annotation/RequiredUserScopes.java
  src/main/java/app/handong/feed/security/enums/UserScope.java
  src/main/java/app/handong/feed/service/GoogleAuthService.java
  src/main/java/app/handong/feed/service/impl/TbadminServiceImpl.java
  src/main/java/app/handong/feed/service/impl/TbuserServiceImpl.java
  src/main/java/app/handong/feed/util/PermissionUtils.java
Labels: enhancement

#140 [Feat] getLatestForDate API 추가 및 Subject → SubjectTag 리팩터링
  .bruno/External/feed/ReadFeed.bru
  .bruno/External/feed/folder.bru
  .bruno/External/folder.bru
  .bruno/External/newsletter/Read All Tag.bru
  .bruno/External/newsletter/Read Tag.bru
  .bruno/External/newsletter/folder.bru
  .bruno/External/subject-tag/Assign Tag to Subject.bru
  .bruno/External/subject-tag/Assign Tags to Subject.bru
  .bruno/External/subject-tag/folder.bru
  .bruno/External/subject-tag/get latest fordate.bru
  .bruno/External/tag/List Tag.bru
  .bruno/External/tag/folder.bru
  src/main/java/app/handong/feed/controller/external/SubjectTagExternalApiController.java
  src/main/java/app/handong/feed/dto/TbSubjectTagDto.java
  src/main/java/app/handong/feed/mapper/TbSubjectTagMapper.java
  src/main/java/app/handong/feed/service/ExternalSubjectService.java
  src/main/java/app/handong/feed/service/ExternalSubjectTagService.java
  src/main/java/app/handong/feed/service/impl/ExternalSubjectTagServiceImpl.java
  src/main/resources/mapper/TbSubjectTagMapper.xml
Labels: enhancement

#144 [BE/FEAT] 주제 태그 할당 완료 상태 업데이트 기능 추가
  .bruno/External/subject/folder.bru
  .bruno/External/subject/update IsTagAssigned True.bru
  src/main/java/app/handong/feed/controller/external/SubjectExternalApiController.java
  src/main/java/app/handong/feed/mapper/TbsubjectMapper.java
  src/main/java/app/handong/feed/service/ExternalFeedService.java
  src/main/java/app/handong/feed/service/ExternalSubjectService.java
  src/main/java/app/handong/feed/service/ExternalSubjectTagService.java
  src/main/java/app/handong/feed/service/TagService.java
  src/main/java/app/handong/feed/service/TbKaFeedService.java
  src/main/java/app/handong/feed/service/TbSubjectTagService.java
  src/main/java/app/handong/feed/service/TbadminService.java
  src/main/java/app/handong/feed/service/TbfeedService.java
  src/main/java/app/handong/feed/service/TbsubjectService.java
  src/main/java/app/handong/feed/service/TbuserService.java
  src/main/java/app/handong/feed/service/UserInteractionService.java
  src/main/java/app/handong/feed/service/impl/ExternalSubjectServiceImpl.java
  src/main/resources/mapper/TbsubjectMapper.xml
Labels: enhancement

#147 [DOCS] PR 및 Issue 템플릿 설정 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/pull_request_template.md
Labels: documentation

#148 [BUG] YAML parsing issue in issue template (follow-up to #147)
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/main.yml
  .github/workflows/pr-build.yml
Labels: bug
